name: Update Pipeline Status

on:
  push:
    branches:
      - toradex/**

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3
    - name: Export Repo Information
      run: |
        echo "current_repo_name=$(basename -s .git $(git config --get remote.origin.url))" >> $GITHUB_ENV
        echo "current_branch_name=${{ github.ref_name }}" >> $GITHUB_ENV
    - name: Checkout Debian Package Pipeline Status Repository
      uses: actions/checkout@v3
      with:
        repository: torizon/debian-package-pipeline-status
        path: debian-package-pipeline-status
        token: ${{ secrets.DEBIAN_PACKAGE_PIPELINE_STATUS_TOKEN }}
    - name: Update Debian Package Pipeline Status README
      run: |
        cd debian-package-pipeline-status
        start_line=$(grep -n "## ${current_repo_name}" README.md | cut -d':' -f1)

        # Check if an entry for the branch already exists
        existing_entry_line=$(grep -n "### ${current_branch_name}" README.md | cut -d':' -f1)

        if [ -z "${existing_entry_line}" ]; then
          # Entry does not exist, add a new entry
          sed -i "${start_line}a\\### ${current_branch_name}  \n[![${current_repo_name} ${current_branch_name}](https://github.com/torizon/${current_repo_name}/actions/workflows/deb-builder.yml/badge.svg?branch=${branch_name})](https://github.com/torizon/${current_repo_name}/actions?query=branch:${branch_name})" README.md
          git config user.name "ci.toradex"
          git config user.email "cicd@toradex.com"
          git add README.md
          git commit -m "Update pipeline status for ${current_repo_name}/${current_branch_name}"
          git push origin main
        fi
